*CLASS LHC_ZHDR_DMP_T_IMP_I DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
*  PRIVATE SECTION.
*    METHODS:
*      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
*        IMPORTING
*           REQUEST requested_authorizations FOR ZHDR_DMP_T_IMP_I
*        RESULT result.
*ENDCLASS.
*
*CLASS LHC_ZHDR_DMP_T_IMP_I IMPLEMENTATION.
*  METHOD GET_GLOBAL_AUTHORIZATIONS.
*  ENDMETHOD.
*ENDCLASS.
