*CLASS LHC_ZHDR_DMP_T_DATA DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
*  PRIVATE SECTION.
*    METHODS:
*      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
*        IMPORTING
*           REQUEST requested_authorizations FOR VersionData
*        RESULT result.
*ENDCLASS.
*
*CLASS LHC_ZHDR_DMP_T_DATA IMPLEMENTATION.
*  METHOD GET_GLOBAL_AUTHORIZATIONS.
*  ENDMETHOD.
*ENDCLASS.
