*CLASS LHC_EXCELSTRUCTURE DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
*  PRIVATE SECTION.
*    METHODS:
*      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
*        IMPORTING
*           REQUEST requested_authorizations FOR ExcelStructure
*        RESULT result.
*ENDCLASS.
*
*CLASS LHC_EXCELSTRUCTURE IMPLEMENTATION.
*  METHOD GET_GLOBAL_AUTHORIZATIONS.
*  ENDMETHOD.
*ENDCLASS.
